# Generated by Django 4.0.6 on 2022-10-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('partner', models.CharField(max_length=255)),
                ('commercial_type', models.IntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('prepend_text', models.CharField(blank=True, max_length=255, null=True)),
                ('prepend_text_url', models.CharField(blank=True, max_length=255, null=True)),
                ('main_banner', models.PositiveIntegerField(blank=True, null=True)),
                ('main_banner_mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('main_banner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_banner', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket_banner_mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket_banner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('openable', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commercials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('openable', models.IntegerField()),
                ('is_free', models.IntegerField()),
                ('reveal', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_commercial', models.IntegerField()),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
    ]
